[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "style", "index.html"]

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "style/input.css", "-o", "style/output.css", "--minify"]