[package]
name = "payment"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
shared = { path = "../shared" }
ordering = { path = "../ordering" }
tokio = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
serde_qs = { workspace = true }
urlencoding = { workspace = true }
hex = "0.4"
qrcode = "0.14"
anyhow = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
mockall = "0.15.0"
test-support = { path = "../test-support" }
